### ISSUE TITLE
Cannot find requirements.txt...

### ISSUE THREAD

**Issue by VinulaUthsara** [yuesongtian/AlphaGAN#1]
Hi,

The requirements.txt does not seem to be included or cannot be found.

**Comment by yuesongtian** [comment]
Hi, thank you for your reminder. I will include requirements.txt.

Most importantly, pytorch 1.3.0, tensorflow-gpu 1.15.0, and numpy 1.19.1 are required.

Thank you.

**Comment by VinulaUthsara** [comment]
Noted with thanks.
