### ISSUE TITLE
Missing instruction on making the "fid_stat" directory (possibly on readme)...

### ISSUE THREAD

**Issue by VinulaUthsara** [yuesongtian/AlphaGAN#3]
Hi,

Encountered the following error when running the search command :

Traceback (most recent call last):
  File "search.py", line 245, in <module>
    main() 
  File "search.py", line 92, in main
    assert os.path.exists(fid_stat)
AssertionError

**Fix :**

Creating a "fid_stat" folder and adding the fid stat file. 

**Suggestion :**

It would be better to add the : 
1). mkdir logs
2). mkdir fid_stat (and upload fid stat file)
instructions to the README.md file 

Would be glad to edit and add a PR for the changes on README as per your permission.

**Comment by yuesongtian** [comment]
Hi, thank you for your suggestion. I will fix this.

**Comment by yuesongtian** [comment]
> Hi,
> 
> Encountered the following error when running the search command :
> 
> Traceback (most recent call last):
> File "search.py", line 245, in
> main()
> File "search.py", line 92, in main
> assert os.path.exists(fid_stat)
> AssertionError
> 
> **Fix :**
> 
> Creating a "fid_stat" folder and adding the fid stat file.
> 
> **Suggestion :**
> 
> It would be better to add the :
> 1). mkdir logs
> 2). mkdir fid_stat (and upload fid stat file)
> instructions to the README.md file
> 
> Would be glad to edit and add a PR for the changes on README as per your permission.

I have updated READEME. Thank you for your remainder.
